### ISSUE TITLE
Support dynamic attributes filtering in filter components

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-dynattr#13]
The `dynattr-api` and `dynatr-ui` modules consist classes that depend on `Filter`:
* `FilteringLookupAction`
* `CategoryAttribute#filterXML`

Related issue - Haulmont/jmix-ui#196

### Solution
The `Filter` supports filtering by dynamic attributes, when adding a dynamic attributes module. It is not necessary to have a `<dynamicAttributes/>` facet on the screen.
Dynamic attributes of all categories are displayed in the conditions tree. 
Note: If the dynamic attribute is an entity, then the entity's internal attributes will not be available for filtering.

### QA
1) Try filtering using `Filter` component for all possible types of dynamic attributes.
2) Try filtering using `PropertyFilter` component for all possible types of dynamic attributes.

**Comment by owlet1997** [comment]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2706-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

### Component Filter
1. Create category -> choose Entity User -> add dynamic attributes with types:
- Date without time
- fixed-point number
- Double
- Integer
-> add atributes to screens -> save ->  apply changes
2. Create some users with fillled dynamic attributes
3. Open User browser -> create filter conditions for dynamic attributes
4. Try to filter entries

AR:
**Date without time, Double, Integer**
there are the same exceptions for these types:
![image](https://user-images.githubusercontent.com/45730069/113385875-0bf84a00-939a-11eb-8e5b-8d29e04f389d.png)
![image](https://user-images.githubusercontent.com/45730069/113385883-10246780-939a-11eb-9381-8a1c65a42468.png)
![image](https://user-images.githubusercontent.com/45730069/113385894-1581b200-939a-11eb-8c8a-2387f229ac02.png)

**Fixed-point number**
incorrect filtering, it's no result with any filter conditions

**Comment by owlet1997** [comment]
### Component PropertyFilter:
1. Field name isn't shown by default and appears after adding "operationEditable=true":
![image](https://user-images.githubusercontent.com/45730069/113387310-1c5df400-939d-11eb-9d75-cf0ebc129b09.png)

2. Caption is not visible after setting property `operationCaptionVisible=true`, but after setting `operationCaptionVisible=false` it appears

3. The same problem with filtering by fields with types as in **Filter component**:
- Date without time
- fixed-point number
- Double
- Integer

**Comment by owlet1997** [comment]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2713-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

**Component Filter**
1. Run app -> Open Dynamic attributes
2. Create category -> choose Entity User -> add dynamic attributes with any (more than 2) types -> add to screens
3. Create any User entities
4. Create filter using dynamic attributes -> set values to two filters with dynamic attribtes

AR:
![image](https://user-images.githubusercontent.com/45730069/113547824-9db4c100-95ff-11eb-8cf5-18dc05c1d775.png)

Exception log:
```
io.jmix.data.impl.jpql.JpqlSyntaxException: Errors found for input JPQL:[select e from d_User e, dynat_CategoryAttributeValue cav, dynat_CategoryAttributeValue cav where (cav.entity.entityId = e.id and cav.dateWithoutTimeValue = :newdateWTptpJKFhR and cav.categoryAttribute.id = '2d7cdc8a-0133-d4a6-fdd1-27e141f4415b' and cav.entity.entityId = e.id and cav.entityValue.entityId = :newentrLSkiWfu and cav.categoryAttribute.id = 'daf4d4c8-6264-c9b8-3f30-8df82256220c') order by e.username]
The identification variable 'cav' cannot be declared more than once
	at io.jmix.data.impl.jpql.QueryParserAstBased.getTree(QueryParserAstBased.java:73)
	at io.jmix.data.impl.jpql.QueryParserAstBased.getAnalyzer(QueryParserAstBased.java:85)
	at io.jmix.data.impl.jpql.QueryParserAstBased.getParamNames(QueryParserAstBased.java:92)
	at io.jmix.data.impl.JpqlQueryBuilder.getQuery(JpqlQueryBuilder.java:166)
	at io.jmix.eclipselink.impl.JpaDataStore.createQuery(JpaDataStore.java:418)
	at io.jmix.eclipselink.impl.JpaDataStore.loadAll(JpaDataStore.java:165)
	at io.jmix.core.datastore.AbstractDataStore.loadList(AbstractDataStore.java:127)
	at io.jmix.core.impl.DataManagerImpl.loadList(DataManagerImpl.java:91)
	at io.jmix.core.impl.SecureDataManagerImpl.loadList(SecureDataManagerImpl.java:49)
	at io.jmix.ui.model.impl.CollectionLoaderImpl.load(CollectionLoaderImpl.java:90)
	at io.jmix.ui.component.impl.AbstractSingleFilterComponent.apply(AbstractSingleFilterComponent.java:307)
	at io.jmix.ui.component.impl.AbstractSingleFilterComponent.onValueChanged(AbstractSingleFilterComponent.java:300)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.component.impl.AbstractComponent.publish(AbstractComponent.java:85)
	at io.jmix.ui.component.impl.ValuePickerImpl.setValueFromUser(ValuePickerImpl.java:148)
	at io.jmix.ui.component.impl.EntityPickerImpl.setValueFromUser(EntityPickerImpl.java:54)
	at io.jmix.ui.builder.LookupBuilderProcessor.handleSelectionWithField(LookupBuilderProcessor.java:223)
	at io.jmix.ui.builder.LookupBuilderProcessor.lambda$buildLookup$1(LookupBuilderProcessor.java:97)
	at io.jmix.ui.screen.StandardLookup.lambda$select$3(StandardLookup.java:197)
	at io.jmix.ui.util.SuccessOperationResult.then(SuccessOperationResult.java:40)
	at io.jmix.ui.screen.StandardLookup.select(StandardLookup.java:197)
	at io.jmix.ui.screen.StandardLookup.select(StandardLookup.java:181)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1607)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Component PropertyFilter**
the same problem if two components were created and applied:
![image](https://user-images.githubusercontent.com/45730069/113548950-8971c380-9601-11eb-9124-671e9168fa6a.png)
