### ISSUE TITLE
Unfetched attribute error when opening existing category attribute for editing

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-dynattr#17]
- create new Category with one attribute
- save both editors

- reopen category
- select attribute in the attributes table -> click Edit

Exception occurs:
```
java.lang.IllegalStateException: Cannot get unfetched attribute [category] from detached object io.jmix.dynattr.model.CategoryAttribute-60dd6c1c-926a-a267-9de9-44911c546af9 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at io.jmix.data.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027)
	at io.jmix.dynattr.model.CategoryAttribute._persistence_checkFetched(CategoryAttribute.java)
	at io.jmix.dynattr.model.CategoryAttribute._persistence_get_category(CategoryAttribute.java)
	at io.jmix.dynattr.model.CategoryAttribute.getCategory(CategoryAttribute.java:278)
	at io.jmix.dynattrui.screen.categoryattr.CategoryAttrsEdit.initTargetScreensTable(CategoryAttrsEdit.java:432)
	at io.jmix.dynattrui.screen.categoryattr.CategoryAttrsEdit.onBeforeShow(CategoryAttrsEdit.java:243)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124)
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:57)
	at io.jmix.ui.sys.ScreensImpl.fireScreenBeforeShowEvent(ScreensImpl.java:1342)
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:363)
	at io.jmix.ui.screen.Screen.show(Screen.java:306)
	at io.jmix.ui.action.list.EditAction.execute(EditAction.java:363)
	at io.jmix.ui.action.list.EditAction.actionPerform(EditAction.java:310)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at jdk.internal.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```
![image](https://user-images.githubusercontent.com/6158807/99371184-02cd7b80-28d8-11eb-8440-2ac64207b80a.png)

**Comment by andreysubbotin** [comment]
Can't reproduced

**Comment by alexbudarov** [comment]
Yes, looks like it was already fixed.
But there is another exception when saving attribute (will create separately).

**Comment by alexbudarov** [comment]
#24
