### ISSUE TITLE
Exception saving category attribute

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-dynattr#24]
- launch app
- Create category. Fill required fields.
- Create attribute. Fill required fields.
- Click OK in Category Attribute dialog.

Exception occurs:
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at io.jmix.dynattrui.screen.categoryattr.CategoryAttrsEdit.preCommitConfiguration(CategoryAttrsEdit.java:969)
	at io.jmix.dynattrui.screen.categoryattr.CategoryAttrsEdit.onPreCommit(CategoryAttrsEdit.java:936)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.model.impl.DataContextImpl.commit(DataContextImpl.java:597)
	at io.jmix.ui.screen.StandardEditor.lambda$commitChanges$4(StandardEditor.java:373)
	at io.jmix.ui.screen.StandardEditor.commitChanges(StandardEditor.java:388)
	at io.jmix.ui.screen.StandardEditor.closeWithCommit(StandardEditor.java:524)
	at io.jmix.ui.screen.StandardEditor.commitAndClose(StandardEditor.java:503)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by andreysubbotin** [comment]
This caused by Haulmont/jmix-dynattr#15 and I have fixed it in the original issue. https://github.com/Haulmont/jmix-dynattr/commit/331572623a73fd5c8f1a2d56a746fc16e48163b8
